# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://www.shenzhen2020.com"
languageCode = "en-AU"
title = "Shenzhen2020"

# Metadata
[params]
  author = "Prestige International"
  description = "Shenzhen2020"

# Hero section (from here on is for icon theme)
[params.hero]
  # img = "images/hero_bg.jpg"
  img = "https://s3-us-west-2.amazonaws.com/website-screenshots-sz2020/ENV9.jpg"
  title = "Shenzhen2020"
  description = "A science-nonfiction film <br> by Maya Rudolph \u0026 Xiaowei Wang"

# Navigation section
[params.nav]
  mission = "About"
  services = "Stills"
  fullimage = "test"
  # contact = "Contact"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = false

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = ""
    title = "About"
    subtitle = ""
    description = "<p>In China\u0027s ubiquitous technosphere, a self-identified cyborg, an idealistic engineer, a millionaire farmer, and a sci-fi writer\u0027s lives are transformed by the Internet and the vanishing space between imagined futures and real life as we approach the year 2020.</p>"

# full image
[params.fullimage]
  enable = true
  img = "https://s3-us-west-2.amazonaws.com/website-screenshots-sz2020/NW2.jpg"

# full image
[params.fullimages]
  enable = true
  img = "https://s3-us-west-2.amazonaws.com/website-screenshots-sz2020/YM3.jpg"


#Services section
[params.services]
  enable = false
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Email us at mayaegrudolph[at]gmail.com or xiaoweirwang[at]gmail.com"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "Email us at mayaegrudolph[at]gmail.com or xiaoweirwang[at]gmail.com"
